"""
BillShield Bill Investigator
Orchestrates: bill retrieval → comparison → validation → anomaly detection → evidence → explanation.

Explanation is generated by Amazon Bedrock (Claude 3) when credentials are configured.
Falls back to deterministic explanation if Bedrock is unavailable.
Mathematical findings are ALWAYS computed by the deterministic engines — Bedrock only explains.
"""
import os
from typing import List, Dict, Any
from ..models.bill import Bill
from ..models.finding import Finding
from ..services.history_engine import HistoryEngine
from ..services.bedrock_service import BedrockService


class BillInvestigatorAgent:

    def investigate(self, current_bill: Bill, historical_bills: List[Bill], findings: List[Finding]) -> Dict[str, Any]:
        print(f"[Investigator] Investigating bill {current_bill.bill_id} ({current_bill.provider})")

        # ── Step 1: Historical comparison ──
        comparison = HistoryEngine.compare(current_bill, historical_bills)
        print(f"[Investigator] Comparison: {comparison}")

        # ── Step 2: Build structured evidence for each finding ──
        evidence_list = self._build_evidence(current_bill, historical_bills, findings, comparison)
        print(f"[Investigator] Built {len(evidence_list)} evidence items")

        # ── Step 3: Generate explanation ──
        # Bedrock receives ONLY verified structured findings — never raw text to interpret numerically.
        use_mock = os.getenv("USE_MOCK_AWS", "true").lower() == "true"
        bedrock_used = False

        if not use_mock and findings:
            print("[Investigator] Calling Amazon Bedrock for explanation...")
            bedrock_result = BedrockService.generate_full_explanation(
                bill=current_bill,
                findings=findings,
                comparison=comparison,
            )
            if bedrock_result:
                explanation = bedrock_result
                bedrock_used = True
                print("[Investigator] Bedrock explanation generated.")
            else:
                print("[Investigator] Bedrock unavailable — using deterministic fallback.")
                explanation = self._deterministic_explanation(current_bill, findings, comparison)
        else:
            explanation = self._deterministic_explanation(current_bill, findings, comparison)

        # ── Step 4: Suggested questions ──
        questions = self._generate_questions(findings, current_bill)

        return {
            "bill_id": current_bill.bill_id,
            "provider": current_bill.provider,
            "summary": self._summary(findings),
            "findings": [f.model_dump() for f in findings],
            "evidence": evidence_list,
            "comparison": comparison,
            "questions": questions,
            "explanation": explanation,
            "explanation_source": "amazon_bedrock" if bedrock_used else "deterministic",
        }

    # ─────────────────────────────────────────────────────────────────────
    # Evidence builder
    # ─────────────────────────────────────────────────────────────────────

    def _build_evidence(
        self,
        current_bill: Bill,
        historical_bills: List[Bill],
        findings: List[Finding],
        comparison: Dict[str, Any],
    ) -> List[Dict[str, Any]]:
        evidence_list = []

        for f in findings:
            ev: Dict[str, Any] = {
                "evidence_id": f.finding_id,
                "finding_type": f.type,
                "title": f.title,
                "source": self._evidence_source(f.type),
            }

            if f.type == "NEW_CHARGE":
                ev["current_bill_text"] = f.description
                ev["historical_check"] = (
                    f"Checked {len(historical_bills)} previous {current_bill.provider} bill(s). "
                    f"This charge was not present in any of them."
                )
                ev["amount"] = f.amount

            elif f.type in ("PRICE_INCREASE", "PRICE_DECREASE"):
                fd = f.evidence or {}
                ev["current_bill_text"] = (
                    f"Current unit price: ₹{fd.get('current_price', 'N/A'):,.2f}"
                    if isinstance(fd.get('current_price'), (int, float))
                    else f.description
                )
                ev["historical_check"] = (
                    f"Previous unit price: ₹{fd.get('previous_price', 'N/A'):,.2f} "
                    f"(from bill {fd.get('previous_bill_id', 'prior bill')})"
                    if isinstance(fd.get('previous_price'), (int, float))
                    else "See historical bills for comparison."
                )
                ev["amount"] = f.amount
                ev["percentage_change"] = fd.get("percentage_change")

            elif f.type in ("TOTAL_MISMATCH", "CALCULATION_DISCREPANCY"):
                fd = f.evidence or {}
                parts = []
                if isinstance(fd.get("subtotal"), (int, float)):
                    parts.append(f"Subtotal: ₹{fd['subtotal']:,.2f}")
                if isinstance(fd.get("discount"), (int, float)) and fd["discount"] > 0:
                    parts.append(f"Discount: −₹{fd['discount']:,.2f}")
                if isinstance(fd.get("fees"), (int, float)) and fd["fees"] > 0:
                    parts.append(f"Fees: ₹{fd['fees']:,.2f}")
                if isinstance(fd.get("tax"), (int, float)) and fd["tax"] > 0:
                    parts.append(f"Tax: ₹{fd['tax']:,.2f}")
                if isinstance(fd.get("calculated_total"), (int, float)):
                    parts.append(f"Calculated total: ₹{fd['calculated_total']:,.2f}")
                ev["current_bill_text"] = " | ".join(parts) or f.description
                ev["historical_check"] = (
                    f"Bill reports total: ₹{fd.get('reported_total', current_bill.total):,.2f}. "
                    f"Difference: ₹{fd.get('difference', f.amount or 0):,.2f}."
                )
                ev["amount"] = f.amount

            elif f.type == "DUPLICATE_CHARGE":
                fd = f.evidence or {}
                ev["current_bill_text"] = (
                    f"'{fd.get('description', '')}' appears {fd.get('occurrences', 2)} times "
                    f"at ₹{fd.get('amount', 0):,.2f} each."
                    if fd else f.description
                )
                ev["historical_check"] = "N/A — check within this bill only."
                ev["amount"] = f.amount

            elif f.type == "UNUSUAL_INCREASE":
                fd = f.evidence or {}
                ev["current_bill_text"] = (
                    f"Current total: ₹{fd.get('current_total', current_bill.total):,.2f}"
                )
                ev["historical_check"] = (
                    f"Previous total: ₹{fd.get('previous_total', comparison.get('previous_total', 0)):,.2f}. "
                    f"Increase: ₹{fd.get('absolute_difference', f.amount or 0):,.2f} "
                    f"({fd.get('percentage_difference', 0):.1f}%)."
                )
                ev["amount"] = f.amount

            else:
                ev["current_bill_text"] = f.description
                ev["historical_check"] = "See finding details."
                ev["amount"] = f.amount

            evidence_list.append(ev)

        return evidence_list

    # ─────────────────────────────────────────────────────────────────────
    # Deterministic explanation (no LLM)
    # ─────────────────────────────────────────────────────────────────────

    def _deterministic_explanation(
        self,
        bill: Bill,
        findings: List[Finding],
        comparison: Dict[str, Any],
    ) -> str:
        lines = ["### Investigation Summary\n"]
        lines.append(f"**Provider:** {bill.provider}")
        lines.append(f"**Bill type:** {bill.bill_type.capitalize()}")
        lines.append(f"**Current total:** ₹{bill.total:,.2f}")

        prev = comparison.get("previous_total", 0)
        if prev > 0:
            diff = comparison.get("absolute_difference", 0)
            pct = comparison.get("percentage_difference", 0)
            direction = "higher" if diff > 0 else "lower" if diff < 0 else "same"
            lines.append(
                f"**Previous total:** ₹{prev:,.2f} — "
                f"this bill is **₹{abs(diff):,.2f} {direction}** "
                f"({abs(pct):.1f}% {'increase' if diff > 0 else 'decrease' if diff < 0 else 'change'})."
            )
        lines.append("")

        if not findings:
            lines.append("✅ **No issues detected.** All calculations are mathematically consistent and no unusual charges were identified.")
        else:
            high = [f for f in findings if f.priority == "HIGH"]
            medium = [f for f in findings if f.priority == "MEDIUM"]
            low = [f for f in findings if f.priority == "LOW"]

            lines.append(f"**{len(findings)} item(s) need your attention:**\n")

            for f in high:
                lines.append(f"🔴 **{f.title}**")
                lines.append(f"   {f.description}")
                lines.append("")

            for f in medium:
                lines.append(f"🟡 **{f.title}**")
                lines.append(f"   {f.description}")
                lines.append("")

            for f in low:
                lines.append(f"🔵 **{f.title}**")
                lines.append(f"   {f.description}")
                lines.append("")

        # Line item breakdown
        if bill.line_items:
            lines.append("\n**Charge breakdown:**")
            for item in bill.line_items:
                lines.append(f"- {item.description}: ₹{item.amount:,.2f}")
            lines.append(f"- **Subtotal: ₹{bill.subtotal:,.2f}**")
            if bill.discount > 0:
                lines.append(f"- Discount: −₹{bill.discount:,.2f}")
            if bill.tax > 0:
                lines.append(f"- GST ({bill.tax_rate:.0f}%): ₹{bill.tax:,.2f}")
            lines.append(f"- **Total: ₹{bill.total:,.2f}**")

        lines.append("\n---\n*Explanation generated deterministically from verified findings. No AI inference was used for numerical results.*")
        return "\n".join(lines)

    # ─────────────────────────────────────────────────────────────────────
    # Suggested questions
    # ─────────────────────────────────────────────────────────────────────

    def _generate_questions(self, findings: List[Finding], bill: Bill) -> List[str]:
        questions = []
        for f in findings:
            if f.type == "NEW_CHARGE":
                fd = f.evidence or {}
                name = fd.get("description", f.title)
                amount = f.amount or 0
                questions.append(f"When was '{name}' added to my account, and what does the ₹{amount:,.2f} charge cover?")
                questions.append(f"Was I notified before '{name}' was added to my bill?")
                questions.append(f"Is '{name}' a mandatory charge or can it be removed?")

            elif f.type == "PRICE_INCREASE":
                fd = f.evidence or {}
                name = fd.get("description", f.title)
                prev = fd.get("previous_price", 0)
                curr = fd.get("current_price", 0)
                questions.append(f"Why did the price of '{name}' increase from ₹{prev:,.2f} to ₹{curr:,.2f}?")
                questions.append(f"Was a notice sent before this price change?")

            elif f.type in ("TOTAL_MISMATCH", "CALCULATION_DISCREPANCY"):
                fd = f.evidence or {}
                questions.append(
                    f"The calculated amount is ₹{fd.get('calculated_total', fd.get('calculated_sum', 0)):,.2f} "
                    f"but the bill shows ₹{fd.get('reported_total', bill.total):,.2f}. Can you explain this discrepancy?"
                )

            elif f.type == "DUPLICATE_CHARGE":
                fd = f.evidence or {}
                questions.append(f"Why does '{fd.get('description', f.title)}' appear more than once on this bill?")

        return questions

    def _summary(self, findings: List[Finding]) -> str:
        if not findings:
            return "No issues detected — all calculations are mathematically consistent."
        high = sum(1 for f in findings if f.priority == "HIGH")
        med = sum(1 for f in findings if f.priority == "MEDIUM")
        low = sum(1 for f in findings if f.priority == "LOW")
        parts = []
        if high:
            parts.append(f"{high} high-priority")
        if med:
            parts.append(f"{med} medium-priority")
        if low:
            parts.append(f"{low} low-priority")
        return f"Found {len(findings)} item(s) worth reviewing: {', '.join(parts)}."

    def _evidence_source(self, finding_type: str) -> str:
        sources = {
            "NEW_CHARGE": "Historical bill comparison",
            "PRICE_INCREASE": "Historical price comparison",
            "PRICE_DECREASE": "Historical price comparison",
            "QUANTITY_CHANGE": "Historical quantity comparison",
            "TOTAL_MISMATCH": "Mathematical validation",
            "CALCULATION_DISCREPANCY": "Mathematical validation",
            "LINE_ITEM_MISMATCH": "Line-item arithmetic check",
            "TAX_MISMATCH": "Tax calculation verification",
            "DUPLICATE_CHARGE": "Duplicate detection",
            "UNUSUAL_INCREASE": "Historical total comparison",
        }
        return sources.get(finding_type, "BillShield analysis engine")
